version: 2.1

orbs:
  gh: circleci/github-cli@1.0

references:
  production_context: &production_context
    - npm

executors:

  publish-npm:
    docker:
      - image: cimg/node:16.17.0


jobs:

  publish-npm:
    executor: publish-npm
    steps:
      - gh/setup
      - checkout
      - run:
          name: Yarn install
          command: yarn

      - gh/release:
          notes-file: CHANGELOG.md
          tag: $(grep '"version":' ./package.json | cut -d\" -f4)
      # command: |
      #   export TAG=$(grep '"version":' ./package.json | cut -d\" -f4)
      #   echo $TAG
      #   gh release create -F CHANGELOG.md $TAG .*
      - run:
          name: publish on npm
          command: yarn publish



workflows:

  release:
    when:
      matches:
        pattern: "^master$"
        value: << pipeline.git.branch >>
    jobs:
      - publish-npm:
          context: *production_context
